name: Python application
on:
  push:
    branches:
      - master
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Build using SAM
      - name: zip Lambda Function
        run: |
          zip -r9 lambda.zip function.py
      - name: AWS Deploy
        run: |
          aws lambda update-function-code --function-name lamda file://function.py
