name: lambda-depl

on:
  push:
    branches:
      - master

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Mahesh414/python@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
        - name: zip lambda
          run: |
            zip -r9 lambda.zip function.py
        - name: AWS Deploy
          run: |
            aws lambda update-function-code --function-name lamda --zip-file fileb://lambda.zip
