name: Python application
on:
  push:
    branches:
      - master
    paths:
      - sns/**
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1  
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: zip Lambda Function
        run: |
          zip -r9 samplee.zip sns.py
      - name: AWS Deploy
        run: |
          aws lambda update-function-code --function-name lamda --zip-file fileb://samplee.zip
