name: Python application
on:
  push:
    branches:
      - master
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: appleboy/lambda-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          function_name: lamda
          source: function.py
  #    - name: zip Lambda Function
  #      run: |
  #        zip -r9 lambda.zip function.py
  #    - name: AWS Deploy
  #      run: |
  #        aws lambda invoke --function-name lamda --zip-file fileb://lambda.zip
          #aws lambda update-function-code --function-name lamda --zip-file fileb://lambda.zip
